export type SkillCategory = 'Replit' | 'Creative' | 'Engineering' | 'Research' | 'Business' | 'Personal';

export type ReplitSkillCatalogItem = {
  id: string;
  nameEn: string;
  nameFa: string;
  category: SkillCategory;
  descriptionEn: string;
  descriptionFa: string;
  instructionsEn: string;
  instructionsFa: string;
  starter: boolean;
};

type CatalogSeed = [
  id: string,
  nameEn: string,
  category: SkillCategory,
  descriptionEn: string,
  starter?: boolean,
  instructionsEn?: string,
  nameFa?: string,
  descriptionFa?: string,
  instructionsFa?: string,
];

const item = ([
  id,
  nameEn,
  category,
  descriptionEn,
  starter = false,
  instructionsEn = descriptionEn,
  nameFa = nameEn,
  descriptionFa = descriptionEn,
  instructionsFa = instructionsEn,
]: CatalogSeed): ReplitSkillCatalogItem => ({
  id,
  nameEn,
  nameFa,
  category,
  descriptionEn,
  descriptionFa,
  instructionsEn,
  instructionsFa,
  starter,
});

// Sourced from the Replit Agent skill directories available in this workspace.
// Starter skills are the practical, ready-to-use subset seeded into FEZI.
export const replitSkillCatalog: ReplitSkillCatalogItem[] = [
  item(['agent-inbox', 'Agent Inbox', 'Replit', 'Manage feedback items, bug reports, and feature requests.']),
  item(['ai-integrations-anthropic', 'Anthropic AI Integration', 'Replit', 'Use the Replit-managed Anthropic integration safely.']),
  item(['ai-integrations-gemini', 'Gemini AI Integration', 'Replit', 'Use the Replit-managed Gemini integration safely.']),
  item(['ai-integrations-openai', 'OpenAI AI Integration', 'Replit', 'Use the Replit-managed OpenAI integration safely.']),
  item(['ai-integrations-openrouter', 'Persian Dark Horse AI Integration', 'Replit', 'Use Persian Dark Horse model routing safely.']),
  item(['artifact-templates', 'Artifact Templates', 'Replit', 'Apply or save reusable web, slides, and design templates.']),
  item(['artifacts', 'Artifacts', 'Replit', 'Create and update registered websites, apps, slides, and data artifacts.']),
  item(['canvas', 'Canvas', 'Replit', 'Create and manipulate visual boards, diagrams, and live previews.']),
  item(['clerk-auth', 'Clerk Authentication', 'Replit', 'Add and troubleshoot authentication with a Replit-managed Clerk tenant.']),
  item(['clerk-auth-e2e-testing-only', 'Clerk E2E Testing', 'Engineering', 'Programmatically sign in test users for Clerk end-to-end tests.']),
  item(['code-review', 'Code Review', 'Engineering', 'Get an architectural review for deep analysis, planning, and debugging.', true, 'Review the requested code or feature for correctness, security, maintainability, and edge cases. Return prioritized findings with concrete fixes and verification steps.', 'بازبینی کد', 'تحلیل معماری، امنیت و کیفیت کد برای پیدا کردن ایرادهای مهم.', 'کد یا قابلیت درخواستی را از نظر صحت، امنیت، نگهداری‌پذیری و حالت‌های مرزی بررسی کن. یافته‌ها را اولویت‌بندی و برای هرکدام راه‌حل و روش بررسی بده.']),
  item(['database', 'Database', 'Replit', 'Create, query, and manage Replit PostgreSQL databases safely.']),
  item(['data-visualization', 'Data Visualization', 'Engineering', 'Build interactive dashboards and dataset explorers.', true, 'Turn data into a clear interactive visualization. Explain the data shape, choose a suitable chart, show important comparisons, and call out uncertainty or missing data.', 'تصویرسازی داده', 'ساخت داشبورد و نمودارهای تعاملی از داده‌ها.', 'داده را به یک تصویرسازی تعاملی و قابل فهم تبدیل کن. ساختار داده را توضیح بده، نمودار مناسب انتخاب کن، مقایسه‌های مهم را نشان بده و کمبود یا عدم قطعیت داده را شفاف بگو.']),
  item(['debug-workflow-ports-issues', 'Workflow Port Debugging', 'Engineering', 'Diagnose workflows that fail to open a port or show a blank preview.']),
  item(['delegation', 'Delegation', 'Replit', 'Delegate independent work to focused subagents.']),
  item(['deployment', 'Deployment', 'Replit', 'Publish apps and investigate production deployment issues.']),
  item(['design', 'Design', 'Creative', 'Delegate frontend design and visual implementation work.']),
  item(['design-exploration', 'Design Exploration', 'Creative', 'Create structured divergent design directions and variants.']),
  item(['design-system-creation', 'Design System Creation', 'Creative', 'Create or import shared tokens and component design systems.']),
  item(['diagnostics', 'Diagnostics', 'Engineering', 'Access static diagnostics and troubleshoot project errors.']),
  item(['environment-secrets', 'Environment Secrets', 'Replit', 'Manage environment variables and secrets without exposing values.']),
  item(['expo', 'Expo', 'Engineering', 'Build and troubleshoot Expo mobile applications.']),
  item(['external-apis', 'External APIs', 'Replit', 'Access external APIs through Replit-managed billing.']),
  item(['follow-up-tasks', 'Follow-up Tasks', 'Replit', 'Identify and propose useful follow-up work.']),
  item(['gamestack-js', 'GameStack JS', 'Engineering', 'Build 2D and 3D games with React Three Fiber.']),
  item(['image-editing', 'Image Editing', 'Creative', 'Restyle, retouch, and transform existing images.']),
  item(['image-search', 'Image Search', 'Creative', 'Find public web images, logos, and reference photos.', true, 'Find a small set of relevant public image references. Include title, source URL, usage context, and any licensing or attribution caution. Do not claim an image was downloaded unless it was actually downloaded.', 'جست‌وجوی تصویر', 'پیدا کردن تصاویر، لوگوها و مراجع تصویری عمومی در وب.', 'چند مرجع تصویری عمومی و مرتبط پیدا کن. عنوان، آدرس منبع، کاربرد و هشدارهای مربوط به مجوز یا attribution را بنویس. فقط وقتی بگو تصویری دانلود شده که واقعاً دانلود شده باشد.']),
  item(['integrations', 'Integrations', 'Replit', 'Search and manage Replit integrations and connectors.']),
  item(['llm-query', 'LLM Query', 'Research', 'Ask a focused internal LLM question about large or noisy content.']),
  item(['media-generation', 'Media Generation', 'Creative', 'Generate AI images, video, audio, and 3D assets.', true, 'Plan a media asset before generating it. State the medium, dimensions or duration, visual direction, prompt, and any missing asset or integration requirement.', 'تولید رسانه', 'برنامه‌ریزی تولید تصویر، ویدئو، صدا و مدل سه‌بعدی با هوش مصنوعی.', 'قبل از تولید رسانه، نوع، ابعاد یا مدت، مسیر بصری، prompt و نیازهای اتصال یا asset را مشخص کن.']),
  item(['merge-resolution', 'Merge Resolution', 'Engineering', 'Resolve changes and reconcile conflicting project updates.']),
  item(['mobile-ui', 'Mobile UI', 'Creative', 'Improve mobile user interfaces and functionality.']),
  item(['mockup-extract', 'Mockup Extract', 'Creative', 'Extract an existing app component into the mockup sandbox.']),
  item(['mockup-graduate', 'Mockup Graduate', 'Creative', 'Integrate an approved mockup into the production app.']),
  item(['mockup-sandbox', 'Mockup Sandbox', 'Creative', 'Create and preview isolated live UI component variants.']),
  item(['monetization', 'Monetization', 'Business', 'Plan payments, subscriptions, checkout, and commerce integrations.']),
  item(['object-storage', 'Object Storage', 'Replit', 'Store persistent user-uploaded and generated files safely.']),
  item(['openscad', 'OpenSCAD', 'Engineering', 'Build parametric printable CAD models from dimensions and primitives.']),
  item(['package-management', 'Package Management', 'Engineering', 'Install and manage packages, runtimes, and system dependencies.']),
  item(['pdf-processing', 'PDF Processing', 'Research', 'Read, render, and understand PDF text, images, and layout.']),
  item(['pnpm-workspace', 'pnpm Workspace', 'Engineering', 'Work safely in a pnpm monorepo with shared packages and APIs.']),
  item(['post-merge-setup', 'Post-Merge Setup', 'Replit', 'Maintain setup actions that run after task merges.']),
  item(['present-chart', 'Present Chart', 'Research', 'Present data inline as a clear chart.']),
  item(['project-analytics', 'Project Analytics', 'Business', 'Track published app traffic, sources, visitors, and custom events.']),
  item(['project-handoff', 'Project Handoff', 'Replit', 'Prepare a project for a clear handoff to another collaborator.']),
  item(['project-scans', 'Project Scans', 'Replit', 'Run tracked security and SEO scans.']),
  item(['project-tasks', 'Project Tasks', 'Replit', 'Create and manage persistent project tasks.']),
  item(['query-integration-data', 'Query Integration Data', 'Business', 'Read and modify data in connected integrations.']),
  item(['react-vite', 'React + Vite', 'Engineering', 'Build and maintain React Vite web applications.', true, 'For React + Vite work, preserve the existing architecture, keep state and API contracts aligned, handle loading and error states, and verify with typecheck, build, and an app preview.', 'ری‌اکت و Vite', 'ساخت و نگهداری اپلیکیشن‌های وب React و Vite.', 'در کارهای React و Vite معماری موجود را حفظ کن، state و قرارداد API را هماهنگ نگه دار، loading و error را پوشش بده و با typecheck، build و preview بررسی کن.']),
  item(['reading-uploaded-files', 'Reading Uploaded Files', 'Replit', 'Read uploaded files with the correct type-specific workflow.']),
  item(['remove-image-background', 'Remove Image Background', 'Creative', 'Remove backgrounds from images and produce transparent PNGs.']),
  item(['replit-auth', 'Replit Auth', 'Replit', 'Integrate Replit Auth with OIDC and PKCE.']),
  item(['replit-auth-e2e-testing-only', 'Replit Auth E2E Testing', 'Engineering', 'Sign in test users for Replit Auth end-to-end tests.']),
  item(['replit-docs', 'Replit Docs', 'Replit', 'Search official Replit documentation before answering platform questions.']),
  item(['repl-setup', 'Repl Setup', 'Replit', 'Set up and configure web apps in the Replit environment.']),
  item(['revenuecat', 'RevenueCat', 'Business', 'Integrate mobile subscriptions and RevenueCat entities.']),
  item(['routines', 'Routines', 'Replit', 'Create repeatable routines for recurring project work.']),
  item(['security-scan', 'Security Scan', 'Engineering', 'Run dependency, SAST, and HoundDog security scans.']),
  item(['shopify', 'Shopify', 'Business', 'Build Shopify storefronts with catalog, inventory, and fulfillment.']),
  item(['skill-authoring', 'Skill Authoring', 'Replit', 'Create reusable skills that extend Agent capabilities.']),
  item(['slides', 'Slides', 'Creative', 'Build, edit, import, and export slide deck artifacts.']),
  item(['streamlit', 'Streamlit', 'Engineering', 'Build interactive Streamlit data applications.']),
  item(['stripe', 'Stripe', 'Business', 'Integrate Stripe payments and related entities.']),
  item(['testing', 'Testing', 'Engineering', 'Plan and run useful automated tests for project behavior.']),
  item(['threat-modeling', 'Threat Modeling', 'Engineering', 'Create a structured threat model for a project.']),
  item(['upgrading-expo', 'Upgrading Expo', 'Engineering', 'Plan a staged Expo SDK upgrade.']),
  item(['validation', 'Validation', 'Engineering', 'Register named shell commands as validation steps.']),
  item(['video-js', 'Video JS', 'Creative', 'Create animated videos with React, Framer Motion, GSAP, and Three.js.']),
  item(['web-search', 'Web Search', 'Research', 'Search the web, fetch pages, and verify current information.', true, 'Research the request with focused searches, fetch authoritative pages when possible, cite the source URLs, separate verified facts from inference, and state when a source is unavailable.', 'جست‌وجوی وب', 'جست‌وجو و بررسی اطلاعات به‌روز از منابع وب.', 'درخواست را با جست‌وجوهای دقیق بررسی کن، در صورت امکان صفحات معتبر را fetch کن، آدرس منابع را بیاور، واقعیت تأییدشده را از استنباط جدا کن و اگر منبعی در دسترس نبود صریح بگو.']),
  item(['whop', 'Whop', 'Business', 'Integrate Whop commerce, payment plans, and checkout.']),
  item(['workflows', 'Workflows', 'Replit', 'Configure, start, stop, and restart application workflows.']),

  item(['ad-creative', 'Ad Creative', 'Creative', 'Create advertising concepts, copy, and creative directions.']),
  item(['ai-recruiter', 'AI Recruiter', 'Business', 'Source candidates, screen resumes, and structure hiring workflows.']),
  item(['ai-sdr', 'AI SDR', 'Business', 'Research prospects and create helpful outbound sales sequences.']),
  item(['ai-secretary', 'AI Secretary', 'Personal', 'Organize meetings, reminders, messages, and personal follow-ups.', true, 'Act as a practical secretary. Clarify priorities, turn requests into a short action list, identify deadlines, and draft concise messages without inventing commitments.', 'منشی هوشمند', 'سازمان‌دهی جلسه‌ها، یادآوری‌ها، پیام‌ها و پیگیری‌های شخصی.', 'مثل یک منشی عملی رفتار کن. اولویت‌ها را روشن کن، درخواست را به فهرست کوتاه اقدام تبدیل کن، deadlineها را مشخص کن و بدون ساختن تعهدات خیالی پیام‌های کوتاه آماده کن.']),
  item(['branding-generator', 'Branding Generator', 'Creative', 'Create brand names, positioning, voice, and visual direction.']),
  item(['business-builder', 'Business Builder', 'Business', 'Turn ideas into business models, offers, and execution plans.']),
  item(['competitive-analysis', 'Competitive Analysis', 'Research', 'Compare competitors, positioning, features, and opportunities.', true, 'Build a grounded competitive analysis. Define the comparison criteria, separate observed facts from assumptions, identify gaps and risks, and finish with actionable positioning recommendations.', 'تحلیل رقابتی', 'مقایسه رقبا، جایگاه، قابلیت‌ها و فرصت‌های بازار.', 'یک تحلیل رقابتی مستند بساز. معیارهای مقایسه را مشخص کن، واقعیت‌های مشاهده‌شده را از فرضیات جدا کن، شکاف‌ها و ریسک‌ها را پیدا کن و در پایان پیشنهادهای قابل اجرا بده.']),
  item(['content-machine', 'Content Machine', 'Creative', 'Create repeatable content systems, calendars, and channel assets.', true, 'Create a content system with audience, objective, pillars, calendar, formats, hooks, and reuse plan. Keep claims factual and adapt each asset to its channel.', 'ماشین محتوا', 'ساخت سیستم تکرارپذیر محتوا، تقویم و محتوای کانال‌ها.', 'یک سیستم محتوا با مخاطب، هدف، ستون‌ها، تقویم، فرمت‌ها، hookها و برنامه بازاستفاده بساز. ادعاها را واقعی نگه دار و هر asset را برای کانال خودش تنظیم کن.']),
  item(['deep-research', 'Deep Research', 'Research', 'Plan and conduct structured research with sources and synthesis.', true, 'Break the question into subquestions, search authoritative sources, record citations, compare conflicting evidence, and end with a concise synthesis and open questions.', 'تحقیق عمیق', 'انجام تحقیق ساختاریافته با منبع و جمع‌بندی.', 'سؤال را به زیرسؤال‌ها تقسیم کن، منابع معتبر را جست‌وجو کن، citation ثبت کن، شواهد متناقض را مقایسه کن و با جمع‌بندی کوتاه و پرسش‌های باز تمام کن.']),
  item(['design-thinker', 'Design Thinker', 'Creative', 'Use user-centered discovery, ideation, prototyping, and testing.']),
  item(['excel-generator', 'Excel Generator', 'Business', 'Create structured spreadsheets, formulas, and downloadable workbooks.']),
  item(['file-converter', 'File Converter', 'Replit', 'Convert documents, images, and media between useful formats.']),
  item(['flashcard-generator', 'Flashcard Generator', 'Personal', 'Turn study material into useful flashcards and review sets.']),
  item(['geo', 'Geo', 'Research', 'Work with locations, maps, geocoding, and geographic context.']),
  item(['github-solution-finder', 'GitHub Solution Finder', 'Engineering', 'Find relevant open-source implementations and repository patterns.']),
  item(['infographic-builder', 'Infographic Builder', 'Creative', 'Turn complex information into a clear visual infographic.']),
  item(['insurance-optimizer', 'Insurance Optimizer', 'Business', 'Compare coverage, risks, and insurance trade-offs.']),
  item(['interview-prep', 'Interview Prep', 'Personal', 'Prepare answers, practice questions, and interview plans.']),
  item(['invoice-generator', 'Invoice Generator', 'Business', 'Create professional invoices with totals and downloadable output.']),
  item(['legal-contract', 'Legal Contract', 'Business', 'Draft and review contracts while flagging legal uncertainty.']),
  item(['look-me-up', 'Look Me Up', 'Research', 'Find public information about a person or organization from sources.']),
  item(['meal-planner', 'Meal Planner', 'Personal', 'Create meal plans with macros, shopping lists, and prep guides.', true, 'Create a practical meal plan around the user’s goals, dietary constraints, budget, schedule, macros, shopping list, and prep steps. Ask before assuming allergies or medical requirements.', 'برنامه‌ریز غذا', 'ساخت برنامه غذایی، لیست خرید و راهنمای آماده‌سازی.', 'برنامه‌ای عملی با توجه به هدف، محدودیت غذایی، بودجه، زمان‌بندی، درشت‌مغذی‌ها، لیست خرید و مراحل آماده‌سازی بساز. درباره حساسیت یا نیاز پزشکی حدس نزن و سؤال کن.']),
  item(['migrate-to-multi-artifact', 'Migrate to Multi-Artifact', 'Replit', 'Prepare a project to support multiple web, mobile, slides, or video artifacts.']),
  item(['personal-shopper', 'Personal Shopper', 'Personal', 'Research products, compare options, and validate purchases.']),
  item(['photo-editor', 'Photo Editor', 'Creative', 'Edit, crop, filter, resize, and optimize images.']),
  item(['podcast-generator', 'Podcast Generator', 'Creative', 'Turn topics into podcast scripts and audio production plans.']),
  item(['podcast-marketing', 'Podcast Marketing', 'Creative', 'Repurpose podcast episodes into posts, clips, and quote cards.']),
  item(['prepare-artifact-template', 'Prepare Artifact Template', 'Replit', 'Package an artifact as a reusable workspace template.']),
  item(['product-manager', 'Product Manager', 'Business', 'Create PRDs, user stories, roadmaps, and prioritization.', true, 'Act as a product manager. Clarify the user problem, target audience, success metrics, scope, risks, user stories, and a prioritized delivery plan.', 'مدیر محصول', 'ساخت PRD، داستان کاربر، roadmap و اولویت‌بندی.', 'مثل مدیر محصول رفتار کن. مشکل کاربر، مخاطب، معیار موفقیت، scope، ریسک‌ها، user storyها و برنامه تحویل اولویت‌بندی‌شده را مشخص کن.']),
  item(['programmatic-seo', 'Programmatic SEO', 'Business', 'Build SEO-optimized pages at scale using templates and data.']),
  item(['real-estate-analyzer', 'Real Estate Analyzer', 'Business', 'Evaluate property returns, affordability, and rent-versus-buy decisions.']),
  item(['recipe-creator', 'Recipe Creator', 'Personal', 'Create recipes and dietary substitutions from ingredients.']),
  item(['recreate-screenshot', 'Recreate Screenshot', 'Creative', 'Recreate a UI from a screenshot with pixel-accurate attention.']),
  item(['replit-admin-api', 'Replit Admin API', 'Replit', 'Work with Enterprise administration, projects, deployments, and audit logs.']),
  item(['replit-migration-guardrails', 'Replit Migration Guardrails', 'Replit', 'Migrate external projects using Replit-native services safely.']),
  item(['resume-maker', 'Resume Maker', 'Personal', 'Build professional resumes with HTML and PDF or DOCX export.', true, 'Build a targeted resume from verified experience. Use strong outcome-based bullets, keep dates and claims accurate, tailor the summary to the role, and offer a clean export structure.', 'رزومه‌ساز', 'ساخت رزومه حرفه‌ای با خروجی HTML، PDF یا DOCX.', 'رزومه‌ای هدفمند بر اساس تجربه‌های تأییدشده بساز. bulletها را نتیجه‌محور کن، تاریخ و ادعاها را دقیق نگه دار، خلاصه را برای نقش موردنظر تنظیم کن و ساختار خروجی تمیز بده.']),
  item(['secondary-hello', 'Secondary Hello', 'Replit', 'Example secondary skill that responds with a wave.']),
  item(['seo-auditor', 'SEO Auditor', 'Business', 'Audit websites for SEO issues and optimization opportunities.', true, 'Audit the page for technical SEO, content, metadata, accessibility, links, performance, and structured data. Prioritize issues by impact and effort, and provide concrete fixes.', 'ممیز SEO', 'بررسی مشکلات SEO و فرصت‌های بهینه‌سازی سایت.', 'صفحه را از نظر SEO فنی، محتوا، metadata، دسترسی‌پذیری، لینک‌ها، performance و structured data بررسی کن. مشکلات را بر اساس اثر و effort اولویت‌بندی و راه‌حل عملی ارائه کن.']),
  item(['skill-creator', 'Skill Creator', 'Replit', 'Create new reusable skills from repeatable workflows.']),
  item(['skill-finder', 'Skill Finder', 'Replit', 'Recommend the right skill for a user goal.']),
  item(['stock-analyzer', 'Stock Analyzer', 'Business', 'Analyze stocks with fundamentals, technical indicators, and reports.']),
  item(['storyboard', 'Storyboard', 'Creative', 'Plan videos with shot lists, scripts, and storyboards.']),
  item(['supplier-research', 'Supplier Research', 'Business', 'Research, evaluate, and compare B2B suppliers.']),
  item(['tax-reviewer', 'Tax Reviewer', 'Business', 'Review tax returns and identify questions or possible deductions.']),
  item(['travel-assistant', 'Travel Assistant', 'Personal', 'Plan trips, itineraries, flights, hotels, and budgets.']),
  item(['video-editing', 'Video Editing', 'Creative', 'Edit video with FFmpeg, subtitles, effects, voiceovers, and reformatting.']),
  item(['website-cloning', 'Website Cloning', 'Engineering', 'Recreate a website as a pixel-accurate React + Vite app.']),
];

export const starterSkills = replitSkillCatalog.filter((skill) => skill.starter);